title: Random webgl snippets

github:
  source:
    branch: master

collections:
  projects:
    output: true
        
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "projects"
    values:
      html: true