title: Random webgl snippets

github:
  source:
    branch: master

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "projects"
    values:
      html: true